eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: product
            uri: http://localhost:8081
            predicates:
              - Path=/api/product/**
          - id: order
            uri: http://localhost:8082
            predicates:
              - Path=/api/order/**
          - id: cart
            uri: http://localhost:8083
            predicates:
              - Path=/api/cart/**
          - id: email
            uri: http://localhost:8084
            predicates:
              - Path=/api/email/**
          - id: take-order
            uri: http://localhost:8085
            predicates:
              - Path=/api/take-order  